-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_Block_entry_proc_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    perf : OUT STD_LOGIC_VECTOR (95 downto 0);
    perf_ap_vld : OUT STD_LOGIC );
end;


architecture behav of dpu_conv_top_Block_entry_proc_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln179_fu_43_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal perf_preg : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln179_cast_fu_33_p4 : STD_LOGIC_VECTOR (64 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    perf_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                perf_preg(0) <= '0';
                perf_preg(1) <= '0';
                perf_preg(2) <= '0';
                perf_preg(3) <= '0';
                perf_preg(4) <= '0';
                perf_preg(5) <= '0';
                perf_preg(6) <= '0';
                perf_preg(7) <= '0';
                perf_preg(8) <= '0';
                perf_preg(9) <= '0';
                perf_preg(10) <= '0';
                perf_preg(11) <= '0';
                perf_preg(12) <= '0';
                perf_preg(13) <= '0';
                perf_preg(14) <= '0';
                perf_preg(15) <= '0';
                perf_preg(16) <= '0';
                perf_preg(17) <= '0';
                perf_preg(18) <= '0';
                perf_preg(19) <= '0';
                perf_preg(20) <= '0';
                perf_preg(21) <= '0';
                perf_preg(22) <= '0';
                perf_preg(23) <= '0';
                perf_preg(24) <= '0';
                perf_preg(25) <= '0';
                perf_preg(26) <= '0';
                perf_preg(27) <= '0';
                perf_preg(28) <= '0';
                perf_preg(29) <= '0';
                perf_preg(30) <= '0';
                perf_preg(31) <= '0';
                perf_preg(32) <= '0';
                perf_preg(33) <= '0';
                perf_preg(34) <= '0';
                perf_preg(35) <= '0';
                perf_preg(36) <= '0';
                perf_preg(37) <= '0';
                perf_preg(38) <= '0';
                perf_preg(39) <= '0';
                perf_preg(40) <= '0';
                perf_preg(41) <= '0';
                perf_preg(42) <= '0';
                perf_preg(43) <= '0';
                perf_preg(44) <= '0';
                perf_preg(45) <= '0';
                perf_preg(46) <= '0';
                perf_preg(47) <= '0';
                perf_preg(48) <= '0';
                perf_preg(49) <= '0';
                perf_preg(50) <= '0';
                perf_preg(51) <= '0';
                perf_preg(52) <= '0';
                perf_preg(53) <= '0';
                perf_preg(54) <= '0';
                perf_preg(55) <= '0';
                perf_preg(56) <= '0';
                perf_preg(57) <= '0';
                perf_preg(58) <= '0';
                perf_preg(59) <= '0';
                perf_preg(60) <= '0';
                perf_preg(61) <= '0';
                perf_preg(62) <= '0';
                perf_preg(63) <= '0';
                perf_preg(64) <= '0';
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        perf_preg(64 downto 0) <= zext_ln179_fu_43_p1(64 downto 0);
                end if; 
            end if;
        end if;
    end process;

    perf_preg(95 downto 65) <= "0000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    perf_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, zext_ln179_fu_43_p1, perf_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            perf <= zext_ln179_fu_43_p1;
        else 
            perf <= perf_preg;
        end if; 
    end process;


    perf_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            perf_ap_vld <= ap_const_logic_1;
        else 
            perf_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln179_cast_fu_33_p4 <= ((ap_const_lv1_1 & p_read) & p_read1);
    zext_ln179_fu_43_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln179_cast_fu_33_p4),96));
end behav;
