-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_Block_entry_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    do_pool_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    do_pool_empty_n : IN STD_LOGIC;
    do_pool_read : OUT STD_LOGIC;
    do_pool_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    do_pool_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ofmap_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    ofmap_empty_n : IN STD_LOGIC;
    ofmap_read : OUT STD_LOGIC;
    ofmap_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ofmap_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of dpu_conv_top_Block_entry_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal do_pool_blk_n : STD_LOGIC;
    signal ofmap_blk_n : STD_LOGIC;
    signal p_read_5_reg_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_read14_reg_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read_6_reg_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal do_pool_read_read_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal do_pool_read_reg_130 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofmap_read_reg_134 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_copy_passthrough_fu_84_ap_start : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_ap_done : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_ap_idle : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_ap_ready : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_ap_start : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_ap_done : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_ap_idle : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_ap_ready : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : STD_LOGIC;
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 : STD_LOGIC;
    signal grp_copy_passthrough_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_maxpool2x2_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dpu_conv_top_copy_passthrough IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
        in_h : IN STD_LOGIC_VECTOR (7 downto 0);
        in_w : IN STD_LOGIC_VECTOR (7 downto 0);
        out_ch : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component dpu_conv_top_maxpool2x2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
        in_h : IN STD_LOGIC_VECTOR (7 downto 0);
        in_w : IN STD_LOGIC_VECTOR (7 downto 0);
        out_ch : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_copy_passthrough_fu_84 : component dpu_conv_top_copy_passthrough
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_copy_passthrough_fu_84_ap_start,
        ap_done => grp_copy_passthrough_fu_84_ap_done,
        ap_idle => grp_copy_passthrough_fu_84_ap_idle,
        ap_ready => grp_copy_passthrough_fu_84_ap_ready,
        m_axi_gmem0_0_AWVALID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => ap_const_logic_0,
        m_axi_gmem0_0_ARADDR => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => ap_const_logic_0,
        m_axi_gmem0_0_RREADY => grp_copy_passthrough_fu_84_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => ap_const_lv8_0,
        m_axi_gmem0_0_RLAST => ap_const_logic_0,
        m_axi_gmem0_0_RID => ap_const_lv1_0,
        m_axi_gmem0_0_RFIFONUM => ap_const_lv11_0,
        m_axi_gmem0_0_RUSER => ap_const_lv1_0,
        m_axi_gmem0_0_RRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BVALID => m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY => grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID => m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER => m_axi_gmem0_0_BUSER,
        ofmap => ofmap_read_reg_134,
        in_h => p_read_6_reg_124,
        in_w => p_read14_reg_118,
        out_ch => p_read_5_reg_112,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 => grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 => grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 => grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 => grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0);

    grp_maxpool2x2_fu_98 : component dpu_conv_top_maxpool2x2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_maxpool2x2_fu_98_ap_start,
        ap_done => grp_maxpool2x2_fu_98_ap_done,
        ap_idle => grp_maxpool2x2_fu_98_ap_idle,
        ap_ready => grp_maxpool2x2_fu_98_ap_ready,
        m_axi_gmem0_0_AWVALID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => ap_const_logic_0,
        m_axi_gmem0_0_ARADDR => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => ap_const_logic_0,
        m_axi_gmem0_0_RREADY => grp_maxpool2x2_fu_98_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => ap_const_lv8_0,
        m_axi_gmem0_0_RLAST => ap_const_logic_0,
        m_axi_gmem0_0_RID => ap_const_lv1_0,
        m_axi_gmem0_0_RFIFONUM => ap_const_lv11_0,
        m_axi_gmem0_0_RUSER => ap_const_lv1_0,
        m_axi_gmem0_0_RRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BVALID => m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY => grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID => m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER => m_axi_gmem0_0_BUSER,
        ofmap => ofmap_read_reg_134,
        in_h => p_read_6_reg_124,
        in_w => p_read14_reg_118,
        out_ch => p_read_5_reg_112,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 => grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_copy_passthrough_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_copy_passthrough_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_copy_passthrough_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_copy_passthrough_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_copy_passthrough_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_maxpool2x2_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_maxpool2x2_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_maxpool2x2_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_maxpool2x2_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_maxpool2x2_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                do_pool_read_reg_130 <= do_pool_dout;
                ofmap_read_reg_134 <= ofmap_dout;
                p_read14_reg_118 <= p_read1;
                p_read_5_reg_112 <= p_read2;
                p_read_6_reg_124 <= p_read;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, do_pool_read_read_fu_72_p2, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (do_pool_read_read_fu_72_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (do_pool_read_read_fu_72_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, do_pool_empty_n, ofmap_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ofmap_empty_n = ap_const_logic_0) or (do_pool_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_ap_done, grp_maxpool2x2_fu_98_ap_done)
    begin
                ap_block_state3_on_subcall_done <= (((grp_maxpool2x2_fu_98_ap_done = ap_const_logic_0) and (do_pool_read_reg_130 = ap_const_lv1_1)) or ((grp_copy_passthrough_fu_84_ap_done = ap_const_logic_0) and (do_pool_read_reg_130 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    do_pool_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, do_pool_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            do_pool_blk_n <= do_pool_empty_n;
        else 
            do_pool_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    do_pool_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            do_pool_read <= ap_const_logic_1;
        else 
            do_pool_read <= ap_const_logic_0;
        end if; 
    end process;

    do_pool_read_read_fu_72_p2 <= do_pool_dout;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((do_pool_read_reg_130 = ap_const_lv1_1)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
            elsif ((do_pool_read_reg_130 = ap_const_lv1_0)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
            else 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= "XXXXXXXXXXXXXXXXX";
            end if;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((do_pool_read_reg_130 = ap_const_lv1_1)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
            elsif ((do_pool_read_reg_130 = ap_const_lv1_0)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
            else 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= ap_const_logic_0;
            end if;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1_assign_proc : process(do_pool_read_reg_130, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1))) then 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((do_pool_read_reg_130 = ap_const_lv1_1)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
            elsif ((do_pool_read_reg_130 = ap_const_lv1_0)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
            else 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= "XXXXXXXXXXXXXXXXX";
            end if;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((do_pool_read_reg_130 = ap_const_lv1_1)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
            elsif ((do_pool_read_reg_130 = ap_const_lv1_0)) then 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
            else 
                dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= ap_const_logic_0;
            end if;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1_assign_proc : process(do_pool_read_reg_130, grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1))) then 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 <= grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_copy_passthrough_fu_84_ap_start <= grp_copy_passthrough_fu_84_ap_start_reg;
    grp_maxpool2x2_fu_98_ap_start <= grp_maxpool2x2_fu_98_ap_start_reg;
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;

    m_axi_gmem0_0_AWADDR_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWADDR <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWADDR <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR;
        else 
            m_axi_gmem0_0_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWBURST_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWBURST <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWBURST <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST;
        else 
            m_axi_gmem0_0_AWBURST <= "XX";
        end if; 
    end process;


    m_axi_gmem0_0_AWCACHE_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWCACHE <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWCACHE <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE;
        else 
            m_axi_gmem0_0_AWCACHE <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWID_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWID <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWID <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID;
        else 
            m_axi_gmem0_0_AWID <= "X";
        end if; 
    end process;


    m_axi_gmem0_0_AWLEN_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWLEN <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWLEN <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN;
        else 
            m_axi_gmem0_0_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWLOCK_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWLOCK <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWLOCK <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK;
        else 
            m_axi_gmem0_0_AWLOCK <= "XX";
        end if; 
    end process;


    m_axi_gmem0_0_AWPROT_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWPROT <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWPROT <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT;
        else 
            m_axi_gmem0_0_AWPROT <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWQOS_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWQOS <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWQOS <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS;
        else 
            m_axi_gmem0_0_AWQOS <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWREGION_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWREGION <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWREGION <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION;
        else 
            m_axi_gmem0_0_AWREGION <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWSIZE_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWSIZE <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWSIZE <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE;
        else 
            m_axi_gmem0_0_AWSIZE <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_0_AWUSER_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWUSER <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWUSER <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER;
        else 
            m_axi_gmem0_0_AWUSER <= "X";
        end if; 
    end process;


    m_axi_gmem0_0_AWVALID_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID, grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_AWVALID <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_AWVALID <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID;
        else 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_0_BREADY_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY, grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_BREADY <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_BREADY <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY;
        else 
            m_axi_gmem0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_RREADY <= ap_const_logic_0;

    m_axi_gmem0_0_WDATA_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WDATA <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WDATA <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA;
        else 
            m_axi_gmem0_0_WDATA <= "XXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_0_WID_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WID <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WID <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID;
        else 
            m_axi_gmem0_0_WID <= "X";
        end if; 
    end process;


    m_axi_gmem0_0_WLAST_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WLAST <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WLAST <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST;
        else 
            m_axi_gmem0_0_WLAST <= 'X';
        end if; 
    end process;


    m_axi_gmem0_0_WSTRB_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WSTRB <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WSTRB <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB;
        else 
            m_axi_gmem0_0_WSTRB <= "X";
        end if; 
    end process;


    m_axi_gmem0_0_WUSER_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WUSER <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WUSER <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER;
        else 
            m_axi_gmem0_0_WUSER <= "X";
        end if; 
    end process;


    m_axi_gmem0_0_WVALID_assign_proc : process(do_pool_read_reg_130, grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID, grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_1)))) then 
            m_axi_gmem0_0_WVALID <= grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (do_pool_read_reg_130 = ap_const_lv1_0)))) then 
            m_axi_gmem0_0_WVALID <= grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID;
        else 
            m_axi_gmem0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    ofmap_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ofmap_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ofmap_blk_n <= ofmap_empty_n;
        else 
            ofmap_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ofmap_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ofmap_read <= ap_const_logic_1;
        else 
            ofmap_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
