-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    bound7 : IN STD_LOGIC_VECTOR (23 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_w : IN STD_LOGIC_VECTOR (7 downto 0);
    bound : IN STD_LOGIC_VECTOR (15 downto 0);
    ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln119 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of dpu_conv_top_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal first_iter_0_reg_644 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_644_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_io_grp1 : BOOLEAN;
    signal icmp_ln119_2_reg_653 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state11_pp0_stage0_iter10_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln115_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem0_blk_n_B : STD_LOGIC;
    signal gmem0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln119_cast_fu_191_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln119_cast_reg_594 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln115_reg_599 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_reg_599_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_603 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_603_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal oh_2_reg_613 : STD_LOGIC_VECTOR (7 downto 0);
    signal oc_2_reg_618 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln115_fu_275_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln115_reg_623 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln115_3_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_3_reg_628 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln117_fu_316_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln117_reg_633 : STD_LOGIC_VECTOR (7 downto 0);
    signal ow_mid2_fu_327_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ow_mid2_reg_638 : STD_LOGIC_VECTOR (7 downto 0);
    signal first_iter_0_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln121_fu_361_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln121_reg_648 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln119_2_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_2_reg_653_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_addr_reg_657 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln119_fu_496_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln119_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln121_fu_530_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln121_reg_683 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal zext_ln121_2_fu_518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln119_1_mid2_fu_478_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ow_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln119_2_fu_367_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal oh_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln117_fu_335_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_fu_104 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln117_1_fu_248_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal oc_fu_108 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln115_4_fu_305_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten27_fu_112 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal add_ln115_1_fu_231_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local : STD_LOGIC;
    signal dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local : STD_LOGIC;
    signal add_ln117_1_fu_242_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln119_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_fu_281_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln117_fu_312_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_349_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln121_fu_357_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_393_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln119_1_fu_404_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln117_fu_400_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln119_1_fu_411_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln119_mid1_fu_421_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal select_ln115_1_fu_428_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln115_1_fu_439_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln119_fu_415_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln119_1_mid1_fu_450_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln115_fu_435_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln119_2_fu_457_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln119_1_fu_461_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln115_2_fu_443_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln119_1_mid2_v_fu_467_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln119_1_mid2_v_cast_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln_fu_499_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_489_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln121_1_fu_508_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln121_1_fu_512_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dpu_conv_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component dpu_conv_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten27_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten27_fu_112 <= ap_const_lv24_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_226_p2 = ap_const_lv1_0))) then 
                    indvar_flatten27_fu_112 <= add_ln115_1_fu_231_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_104 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln115_fu_226_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_104 <= select_ln117_1_fu_248_p3;
                end if;
            end if; 
        end if;
    end process;

    oc_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    oc_fu_108 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln115_reg_599 = ap_const_lv1_0))) then 
                    oc_fu_108 <= select_ln115_4_fu_305_p3;
                end if;
            end if; 
        end if;
    end process;

    oh_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    oh_fu_100 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln115_reg_599 = ap_const_lv1_0))) then 
                    oh_fu_100 <= select_ln117_fu_335_p3;
                end if;
            end if; 
        end if;
    end process;

    ow_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ow_fu_96 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln115_reg_599 = ap_const_lv1_0))) then 
                    ow_fu_96 <= add_ln119_2_fu_367_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln115_reg_623 <= add_ln115_fu_275_p2;
                add_ln117_reg_633 <= add_ln117_fu_316_p2;
                add_ln121_reg_648 <= add_ln121_fu_361_p2;
                first_iter_0_reg_644 <= first_iter_0_fu_343_p2;
                first_iter_0_reg_644_pp0_iter3_reg <= first_iter_0_reg_644;
                gmem0_addr_reg_657 <= add_ln119_1_mid2_fu_478_p2;
                icmp_ln119_2_reg_653 <= icmp_ln119_2_fu_373_p2;
                icmp_ln119_2_reg_653_pp0_iter3_reg <= icmp_ln119_2_reg_653;
                icmp_ln119_2_reg_653_pp0_iter4_reg <= icmp_ln119_2_reg_653_pp0_iter3_reg;
                icmp_ln119_2_reg_653_pp0_iter5_reg <= icmp_ln119_2_reg_653_pp0_iter4_reg;
                icmp_ln119_2_reg_653_pp0_iter6_reg <= icmp_ln119_2_reg_653_pp0_iter5_reg;
                icmp_ln119_2_reg_653_pp0_iter7_reg <= icmp_ln119_2_reg_653_pp0_iter6_reg;
                icmp_ln119_2_reg_653_pp0_iter8_reg <= icmp_ln119_2_reg_653_pp0_iter7_reg;
                icmp_ln119_2_reg_653_pp0_iter9_reg <= icmp_ln119_2_reg_653_pp0_iter8_reg;
                oc_2_reg_618 <= oc_fu_108;
                oh_2_reg_613 <= oh_fu_100;
                ow_mid2_reg_638 <= ow_mid2_fu_327_p3;
                select_ln115_3_reg_628 <= select_ln115_3_fu_298_p3;
                select_ln121_reg_683 <= select_ln121_fu_530_p3;
                trunc_ln119_reg_662 <= trunc_ln119_fu_496_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln115_reg_599 <= icmp_ln115_fu_226_p2;
                icmp_ln117_reg_603 <= icmp_ln117_fu_237_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln115_reg_599_pp0_iter2_reg <= icmp_ln115_reg_599;
                icmp_ln117_reg_603_pp0_iter2_reg <= icmp_ln117_reg_603;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                    zext_ln119_cast_reg_594(7 downto 0) <= zext_ln119_cast_fu_191_p1(7 downto 0);
            end if;
        end if;
    end process;
    zext_ln119_cast_reg_594(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln115_1_fu_231_p2 <= std_logic_vector(unsigned(indvar_flatten27_fu_112) + unsigned(ap_const_lv24_1));
    add_ln115_fu_275_p2 <= std_logic_vector(unsigned(oc_fu_108) + unsigned(ap_const_lv8_1));
    add_ln117_1_fu_242_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_104) + unsigned(ap_const_lv16_1));
    add_ln117_fu_316_p2 <= std_logic_vector(unsigned(select_ln115_fu_281_p3) + unsigned(ap_const_lv8_1));
    add_ln119_1_fu_461_p2 <= std_logic_vector(unsigned(zext_ln115_fu_435_p1) + unsigned(zext_ln119_2_fu_457_p1));
    add_ln119_1_mid2_fu_478_p2 <= std_logic_vector(unsigned(add_ln119_1_mid2_v_cast_fu_474_p1) + unsigned(ofmap));
    add_ln119_1_mid2_v_cast_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln119_1_mid2_v_fu_467_p3),64));
    add_ln119_1_mid2_v_fu_467_p3 <= 
        add_ln119_1_fu_461_p2 when (select_ln115_3_reg_628(0) = '1') else 
        select_ln115_2_fu_443_p3;
    add_ln119_2_fu_367_p2 <= std_logic_vector(unsigned(ow_mid2_fu_327_p3) + unsigned(ap_const_lv8_1));
    add_ln119_fu_415_p2 <= std_logic_vector(unsigned(zext_ln117_fu_400_p1) + unsigned(zext_ln119_1_fu_411_p1));
    add_ln121_1_fu_512_p2 <= std_logic_vector(unsigned(tmp_3_fu_489_p3) + unsigned(zext_ln121_1_fu_508_p1));
    add_ln121_fu_361_p2 <= std_logic_vector(unsigned(tmp_fu_349_p3) + unsigned(zext_ln121_fu_357_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter10, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1)) or ((m_axi_gmem0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter10, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1)) or ((m_axi_gmem0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter10, m_axi_gmem0_0_WREADY, ap_block_state5_io_grp1, ap_block_state11_pp0_stage0_iter10_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10_grp1)) or ((m_axi_gmem0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp0_stage0_iter10_grp1_assign_proc : process(m_axi_gmem0_0_BVALID, icmp_ln119_2_reg_653_pp0_iter9_reg)
    begin
                ap_block_state11_pp0_stage0_iter10_grp1 <= ((icmp_ln119_2_reg_653_pp0_iter9_reg = ap_const_lv1_1) and (m_axi_gmem0_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state5_io_grp1_assign_proc : process(m_axi_gmem0_0_AWREADY, first_iter_0_reg_644_pp0_iter3_reg)
    begin
                ap_block_state5_io_grp1 <= ((m_axi_gmem0_0_AWREADY = ap_const_logic_0) and (first_iter_0_reg_644_pp0_iter3_reg = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln115_fu_226_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln115_fu_226_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln115_reg_599_pp0_iter2_reg)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln115_reg_599_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= zext_ln121_2_fu_518_p1(17 - 1 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local <= ap_const_logic_1;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= zext_ln121_2_fu_518_p1(17 - 1 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local;

    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local <= ap_const_logic_1;
        else 
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_322_p2 <= (select_ln115_3_fu_298_p3 or icmp_ln117_reg_603);
    first_iter_0_fu_343_p2 <= "1" when (ow_mid2_fu_327_p3 = ap_const_lv8_0) else "0";

    gmem0_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem0_0_AWREADY, first_iter_0_reg_644_pp0_iter3_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (first_iter_0_reg_644_pp0_iter3_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_AW <= m_axi_gmem0_0_AWREADY;
        else 
            gmem0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_gmem0_0_BVALID, icmp_ln119_2_reg_653_pp0_iter9_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln119_2_reg_653_pp0_iter9_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_B <= m_axi_gmem0_0_BVALID;
        else 
            gmem0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem0_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem0_blk_n_W <= m_axi_gmem0_0_WREADY;
        else 
            gmem0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln115_fu_226_p2 <= "1" when (indvar_flatten27_fu_112 = bound7) else "0";
    icmp_ln117_fu_237_p2 <= "1" when (indvar_flatten_fu_104 = bound) else "0";
    icmp_ln119_1_fu_293_p2 <= "1" when (ow_fu_96 = in_w) else "0";
    icmp_ln119_2_fu_373_p2 <= "1" when (add_ln119_2_fu_367_p2 = in_w) else "0";
    icmp_ln119_fu_288_p2 <= "1" when (in_w = ap_const_lv8_0) else "0";
    lshr_ln_fu_499_p4 <= ow_mid2_reg_638(7 downto 1);
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= gmem0_addr_reg_657;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= zext_ln119_cast_reg_594(32 - 1 downto 0);
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter4, first_iter_0_reg_644_pp0_iter3_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (first_iter_0_reg_644_pp0_iter3_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter10, icmp_ln119_2_reg_653_pp0_iter9_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln119_2_reg_653_pp0_iter9_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_0_WDATA <= select_ln121_reg_683;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv1_1;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    ow_mid2_fu_327_p3 <= 
        ap_const_lv8_0 when (empty_fu_322_p2(0) = '1') else 
        ow_fu_96;
    select_ln115_1_fu_428_p3 <= 
        shl_ln119_mid1_fu_421_p3 when (icmp_ln117_reg_603_pp0_iter2_reg(0) = '1') else 
        shl_ln_fu_393_p3;
    select_ln115_2_fu_443_p3 <= 
        zext_ln115_1_fu_439_p1 when (icmp_ln117_reg_603_pp0_iter2_reg(0) = '1') else 
        add_ln119_fu_415_p2;
    select_ln115_3_fu_298_p3 <= 
        icmp_ln119_fu_288_p2 when (icmp_ln117_reg_603(0) = '1') else 
        icmp_ln119_1_fu_293_p2;
    select_ln115_4_fu_305_p3 <= 
        add_ln115_fu_275_p2 when (icmp_ln117_reg_603(0) = '1') else 
        oc_fu_108;
    select_ln115_fu_281_p3 <= 
        ap_const_lv8_0 when (icmp_ln117_reg_603(0) = '1') else 
        oh_fu_100;
    select_ln117_1_fu_248_p3 <= 
        ap_const_lv16_1 when (icmp_ln117_fu_237_p2(0) = '1') else 
        add_ln117_1_fu_242_p2;
    select_ln117_fu_335_p3 <= 
        add_ln117_fu_316_p2 when (select_ln115_3_fu_298_p3(0) = '1') else 
        select_ln115_fu_281_p3;
    select_ln121_fu_530_p3 <= 
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 when (trunc_ln119_reg_662(0) = '1') else 
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0;
    shl_ln119_1_fu_404_p3 <= (oh_2_reg_613 & ap_const_lv6_0);
    shl_ln119_1_mid1_fu_450_p3 <= (add_ln117_reg_633 & ap_const_lv6_0);
    shl_ln119_mid1_fu_421_p3 <= (add_ln115_reg_623 & ap_const_lv12_0);
    shl_ln_fu_393_p3 <= (oc_2_reg_618 & ap_const_lv12_0);
    tmp_3_fu_489_p3 <= (add_ln121_reg_648 & ap_const_lv5_0);
    tmp_fu_349_p3 <= (trunc_ln117_fu_312_p1 & ap_const_lv6_0);
    trunc_ln117_fu_312_p1 <= select_ln115_4_fu_305_p3(6 - 1 downto 0);
    trunc_ln119_fu_496_p1 <= ow_mid2_reg_638(1 - 1 downto 0);
    zext_ln115_1_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_mid1_fu_421_p3),21));
    zext_ln115_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln115_1_fu_428_p3),21));
    zext_ln117_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_393_p3),21));
    zext_ln119_1_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_1_fu_404_p3),21));
    zext_ln119_2_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln119_1_mid1_fu_450_p3),21));
    zext_ln119_cast_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln119),64));
    zext_ln121_1_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_499_p4),17));
    zext_ln121_2_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln121_1_fu_512_p2),64));
    zext_ln121_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln117_fu_335_p3),12));
end behav;
