-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpu_conv_top_copy_passthrough is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
    in_h : IN STD_LOGIC_VECTOR (7 downto 0);
    in_w : IN STD_LOGIC_VECTOR (7 downto 0);
    out_ch : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of dpu_conv_top_copy_passthrough is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bound_fu_88_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal bound_reg_114 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal bound7_fu_101_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal bound7_reg_125 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_idle : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : STD_LOGIC;
    signal grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bound_fu_88_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal bound_fu_88_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bound7_fu_101_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal bound7_fu_101_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal bound7_fu_101_p00 : STD_LOGIC_VECTOR (23 downto 0);
    signal bound7_fu_101_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal bound_fu_88_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal bound_fu_88_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component dpu_conv_top_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        bound7 : IN STD_LOGIC_VECTOR (23 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 : OUT STD_LOGIC;
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        in_w : IN STD_LOGIC_VECTOR (7 downto 0);
        bound : IN STD_LOGIC_VECTOR (15 downto 0);
        ofmap : IN STD_LOGIC_VECTOR (63 downto 0);
        zext_ln119 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component dpu_conv_top_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dpu_conv_top_mul_8ns_16ns_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64 : component dpu_conv_top_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start,
        ap_done => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done,
        ap_idle => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_idle,
        ap_ready => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready,
        m_axi_gmem0_0_AWVALID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => ap_const_logic_0,
        m_axi_gmem0_0_ARADDR => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => ap_const_logic_0,
        m_axi_gmem0_0_RREADY => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => ap_const_lv8_0,
        m_axi_gmem0_0_RLAST => ap_const_logic_0,
        m_axi_gmem0_0_RID => ap_const_lv1_0,
        m_axi_gmem0_0_RFIFONUM => ap_const_lv11_0,
        m_axi_gmem0_0_RUSER => ap_const_lv1_0,
        m_axi_gmem0_0_RRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BVALID => m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID => m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER => m_axi_gmem0_0_BUSER,
        bound7 => bound7_reg_125,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 => grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0 => dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0,
        in_w => in_w,
        bound => bound_reg_114,
        ofmap => ofmap,
        zext_ln119 => in_w);

    mul_8ns_8ns_16_1_1_U183 : component dpu_conv_top_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => bound_fu_88_p0,
        din1 => bound_fu_88_p1,
        dout => bound_fu_88_p2);

    mul_8ns_16ns_24_1_1_U184 : component dpu_conv_top_mul_8ns_16ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 16,
        dout_WIDTH => 24)
    port map (
        din0 => bound7_fu_101_p0,
        din1 => bound7_fu_101_p1,
        dout => bound7_fu_101_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound7_reg_125 <= bound7_fu_101_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bound_reg_114 <= bound_fu_88_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done)
    begin
        if ((grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done, ap_CS_fsm_state3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound7_fu_101_p0 <= bound7_fu_101_p00(8 - 1 downto 0);
    bound7_fu_101_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_ch),24));
    bound7_fu_101_p1 <= bound7_fu_101_p10(16 - 1 downto 0);
    bound7_fu_101_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound_reg_114),24));
    bound_fu_88_p0 <= bound_fu_88_p00(8 - 1 downto 0);
    bound_fu_88_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_h),16));
    bound_fu_88_p1 <= bound_fu_88_p10(8 - 1 downto 0);
    bound_fu_88_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_w),16));
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg;
    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR;
    m_axi_gmem0_0_AWBURST <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST;
    m_axi_gmem0_0_AWCACHE <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE;
    m_axi_gmem0_0_AWID <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID;
    m_axi_gmem0_0_AWLEN <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN;
    m_axi_gmem0_0_AWLOCK <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK;
    m_axi_gmem0_0_AWPROT <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT;
    m_axi_gmem0_0_AWQOS <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS;
    m_axi_gmem0_0_AWREGION <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION;
    m_axi_gmem0_0_AWSIZE <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE;
    m_axi_gmem0_0_AWUSER <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER;
    m_axi_gmem0_0_AWVALID <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID;
    m_axi_gmem0_0_BREADY <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY;
    m_axi_gmem0_0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_0_WDATA <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA;
    m_axi_gmem0_0_WID <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID;
    m_axi_gmem0_0_WLAST <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST;
    m_axi_gmem0_0_WSTRB <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB;
    m_axi_gmem0_0_WUSER <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER;
    m_axi_gmem0_0_WVALID <= grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID;
end behav;
