[hls]
relative_roots=D:/project/DPU_Project/DPU_HLS
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv3x3_relu/OW_LOOP  
syn.directive.loop_flatten=conv3x3_relu/OH_LOOP  
syn.directive.loop_flatten=dpu_conv_top/POOL_H  
syn.directive.loop_flatten=dpu_conv_top/POOL_OC  
syn.directive.loop_flatten=dpu_conv_top/COPY_H  
syn.directive.loop_flatten=dpu_conv_top/COPY_OC  


