# Inferred from performance & pipeline pragmas/directives
set_directive_loop_flatten conv3x3_relu/OW_LOOP
set_directive_loop_flatten conv3x3_relu/OH_LOOP
set_directive_loop_flatten dpu_conv_top/POOL_H
set_directive_loop_flatten dpu_conv_top/POOL_OC
set_directive_loop_flatten dpu_conv_top/COPY_H
set_directive_loop_flatten dpu_conv_top/COPY_OC
