[hls]
relative_roots=D:/project/DPU_HLS
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv3x3_relu/OW_LOOP  
syn.directive.loop_flatten=conv3x3_relu/OH_LOOP  
syn.directive.array_partition=dpu_conv_top/dpu_conv_top(ap_int<8> (*) [64][64], ap_int<8> (*) [64][3][3], ap_int<32>*, ap_int<8> (*) [64][64], ap_uint<8>, ap_uint<8>, ap_uint<8>, ap_uint<8>, ap_uint<1>, ap_uint<1>, perf_counters_t&)::conv_buf dim=3 type=cyclic factor=2 variable=dpu_conv_top(ap_int<8> (*) [64][64], ap_int<8> (*) [64][3][3], ap_int<32>*, ap_int<8> (*) [64][64], ap_uint<8>, ap_uint<8>, ap_uint<8>, ap_uint<8>, ap_uint<1>, ap_uint<1>, perf_counters_t&)::conv_buf
syn.directive.loop_flatten=maxpool2x2/POOL_H  
syn.directive.loop_flatten=maxpool2x2/POOL_OC  
syn.directive.loop_flatten=copy_passthrough/COPY_H  
syn.directive.loop_flatten=copy_passthrough/COPY_OC  


