// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_Block_entry_proc_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        perf,
        perf_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
output  [95:0] perf;
output   perf_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[95:0] perf;
reg perf_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [95:0] zext_ln179_fu_43_p1;
reg   [95:0] perf_preg;
wire   [64:0] zext_ln179_cast_fu_33_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 perf_preg = 96'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                perf_preg[0] <= 1'b0;
        perf_preg[1] <= 1'b0;
        perf_preg[2] <= 1'b0;
        perf_preg[3] <= 1'b0;
        perf_preg[4] <= 1'b0;
        perf_preg[5] <= 1'b0;
        perf_preg[6] <= 1'b0;
        perf_preg[7] <= 1'b0;
        perf_preg[8] <= 1'b0;
        perf_preg[9] <= 1'b0;
        perf_preg[10] <= 1'b0;
        perf_preg[11] <= 1'b0;
        perf_preg[12] <= 1'b0;
        perf_preg[13] <= 1'b0;
        perf_preg[14] <= 1'b0;
        perf_preg[15] <= 1'b0;
        perf_preg[16] <= 1'b0;
        perf_preg[17] <= 1'b0;
        perf_preg[18] <= 1'b0;
        perf_preg[19] <= 1'b0;
        perf_preg[20] <= 1'b0;
        perf_preg[21] <= 1'b0;
        perf_preg[22] <= 1'b0;
        perf_preg[23] <= 1'b0;
        perf_preg[24] <= 1'b0;
        perf_preg[25] <= 1'b0;
        perf_preg[26] <= 1'b0;
        perf_preg[27] <= 1'b0;
        perf_preg[28] <= 1'b0;
        perf_preg[29] <= 1'b0;
        perf_preg[30] <= 1'b0;
        perf_preg[31] <= 1'b0;
        perf_preg[32] <= 1'b0;
        perf_preg[33] <= 1'b0;
        perf_preg[34] <= 1'b0;
        perf_preg[35] <= 1'b0;
        perf_preg[36] <= 1'b0;
        perf_preg[37] <= 1'b0;
        perf_preg[38] <= 1'b0;
        perf_preg[39] <= 1'b0;
        perf_preg[40] <= 1'b0;
        perf_preg[41] <= 1'b0;
        perf_preg[42] <= 1'b0;
        perf_preg[43] <= 1'b0;
        perf_preg[44] <= 1'b0;
        perf_preg[45] <= 1'b0;
        perf_preg[46] <= 1'b0;
        perf_preg[47] <= 1'b0;
        perf_preg[48] <= 1'b0;
        perf_preg[49] <= 1'b0;
        perf_preg[50] <= 1'b0;
        perf_preg[51] <= 1'b0;
        perf_preg[52] <= 1'b0;
        perf_preg[53] <= 1'b0;
        perf_preg[54] <= 1'b0;
        perf_preg[55] <= 1'b0;
        perf_preg[56] <= 1'b0;
        perf_preg[57] <= 1'b0;
        perf_preg[58] <= 1'b0;
        perf_preg[59] <= 1'b0;
        perf_preg[60] <= 1'b0;
        perf_preg[61] <= 1'b0;
        perf_preg[62] <= 1'b0;
        perf_preg[63] <= 1'b0;
        perf_preg[64] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                        perf_preg[64 : 0] <= zext_ln179_fu_43_p1[64 : 0];
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        perf = zext_ln179_fu_43_p1;
    end else begin
        perf = perf_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        perf_ap_vld = 1'b1;
    end else begin
        perf_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign zext_ln179_cast_fu_33_p4 = {{{{1'd1}, {p_read}}}, {p_read1}};

assign zext_ln179_fu_43_p1 = zext_ln179_cast_fu_33_p4;

always @ (posedge ap_clk) begin
    perf_preg[95:65] <= 31'b0000000000000000000000000000000;
end

endmodule //dpu_conv_top_Block_entry_proc_2
