// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_copy_passthrough (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        ofmap,
        in_h,
        in_w,
        out_ch,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] ofmap;
input  [7:0] in_h;
input  [7:0] in_w;
input  [7:0] out_ch;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] bound_fu_88_p2;
reg   [15:0] bound_reg_114;
wire    ap_CS_fsm_state2;
wire   [23:0] bound7_fu_101_p2;
reg   [23:0] bound7_reg_125;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_idle;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID;
wire   [31:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARID;
wire   [31:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARUSER;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_RREADY;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY;
wire   [16:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
wire   [16:0] grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
wire    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
reg    grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [7:0] bound_fu_88_p0;
wire   [7:0] bound_fu_88_p1;
wire   [7:0] bound7_fu_101_p0;
wire   [15:0] bound7_fu_101_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [23:0] bound7_fu_101_p00;
wire   [23:0] bound7_fu_101_p10;
wire   [15:0] bound_fu_88_p00;
wire   [15:0] bound_fu_88_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg = 1'b0;
end

dpu_conv_top_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start),
    .ap_done(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done),
    .ap_idle(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_idle),
    .ap_ready(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(m_axi_gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(m_axi_gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(8'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(11'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(m_axi_gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(m_axi_gmem0_0_BRESP),
    .m_axi_gmem0_0_BID(m_axi_gmem0_0_BID),
    .m_axi_gmem0_0_BUSER(m_axi_gmem0_0_BUSER),
    .bound7(bound7_reg_125),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0(grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0),
    .in_w(in_w),
    .bound(bound_reg_114),
    .ofmap(ofmap),
    .zext_ln119(in_w)
);

dpu_conv_top_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U183(
    .din0(bound_fu_88_p0),
    .din1(bound_fu_88_p1),
    .dout(bound_fu_88_p2)
);

dpu_conv_top_mul_8ns_16ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16ns_24_1_1_U184(
    .din0(bound7_fu_101_p0),
    .din1(bound7_fu_101_p1),
    .dout(bound7_fu_101_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_ready == 1'b1)) begin
            grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound7_reg_125 <= bound7_fu_101_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_reg_114 <= bound_fu_88_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign bound7_fu_101_p0 = bound7_fu_101_p00;

assign bound7_fu_101_p00 = out_ch;

assign bound7_fu_101_p1 = bound7_fu_101_p10;

assign bound7_fu_101_p10 = bound_reg_114;

assign bound_fu_88_p0 = bound_fu_88_p00;

assign bound_fu_88_p00 = in_h;

assign bound_fu_88_p1 = bound_fu_88_p10;

assign bound_fu_88_p10 = in_w;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;

assign grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_ap_start_reg;

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWADDR;

assign m_axi_gmem0_0_AWBURST = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWBURST;

assign m_axi_gmem0_0_AWCACHE = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWCACHE;

assign m_axi_gmem0_0_AWID = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWID;

assign m_axi_gmem0_0_AWLEN = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLEN;

assign m_axi_gmem0_0_AWLOCK = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWLOCK;

assign m_axi_gmem0_0_AWPROT = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWPROT;

assign m_axi_gmem0_0_AWQOS = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWQOS;

assign m_axi_gmem0_0_AWREGION = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWREGION;

assign m_axi_gmem0_0_AWSIZE = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWSIZE;

assign m_axi_gmem0_0_AWUSER = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWUSER;

assign m_axi_gmem0_0_AWVALID = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_AWVALID;

assign m_axi_gmem0_0_BREADY = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_BREADY;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WDATA;

assign m_axi_gmem0_0_WID = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WID;

assign m_axi_gmem0_0_WLAST = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WLAST;

assign m_axi_gmem0_0_WSTRB = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WSTRB;

assign m_axi_gmem0_0_WUSER = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WUSER;

assign m_axi_gmem0_0_WVALID = grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64_m_axi_gmem0_0_WVALID;

endmodule //dpu_conv_top_copy_passthrough
