

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105"],
		"CDFG" : "dpu_conv_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "618", "EstimateLatencyMax" : "167578581",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_4", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_5", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_6", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem0_7", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_4", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_5", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_6", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1_7", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_conv3x3_relu_fu_393", "Port" : "gmem2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "77", "SubInstance" : "grp_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W_fu_479", "Port" : "gmem2", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "79", "SubInstance" : "grp_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W_fu_493", "Port" : "gmem2", "Inst_start_state" : "5", "Inst_end_state" : "4"}]},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "77", "SubInstance" : "grp_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W_fu_479", "Port" : "gmem0", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "79", "SubInstance" : "grp_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W_fu_493", "Port" : "gmem0", "Inst_start_state" : "5", "Inst_end_state" : "4"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_scratch", "Type" : "None", "Direction" : "I"},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_pool", "Type" : "None", "Direction" : "I"},
			{"Name" : "perf", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393", "Parent" : "0", "Child" : ["2", "76"],
		"CDFG" : "conv3x3_relu",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "612", "EstimateLatencyMax" : "150997185",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_0", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_4", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_5", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_6", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem0_7", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_0", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_4", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_5", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_6", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem1_7", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Port" : "gmem2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "conv_buf", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "OC_LOOP", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "13", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state13"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352", "Parent" : "1", "Child" : ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75"],
		"CDFG" : "conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "599", "EstimateLatencyMax" : "2359319",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cycle_count_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "shl_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln23_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound7", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln23_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln23", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_buf", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln33_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_3_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_3_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_4_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_4_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_4_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_4_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_5_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_5_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_5_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_5_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_6_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_6_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_6_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_6_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_7_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_7_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_7_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_7_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "select_ln31_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "OH_LOOP_OW_LOOP_IC_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "72", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage22", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage22_subdone", "QuitState" : "ap_ST_fsm_pp0_stage22", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage22_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U1", "Parent" : "2"},
	{"ID" : "4", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U2", "Parent" : "2"},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U3", "Parent" : "2"},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U4", "Parent" : "2"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U5", "Parent" : "2"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U6", "Parent" : "2"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U7", "Parent" : "2"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U8", "Parent" : "2"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U9", "Parent" : "2"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U10", "Parent" : "2"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U11", "Parent" : "2"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U12", "Parent" : "2"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U13", "Parent" : "2"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U14", "Parent" : "2"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U15", "Parent" : "2"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U16", "Parent" : "2"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U17", "Parent" : "2"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U18", "Parent" : "2"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U19", "Parent" : "2"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U20", "Parent" : "2"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U21", "Parent" : "2"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U22", "Parent" : "2"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U23", "Parent" : "2"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U24", "Parent" : "2"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U25", "Parent" : "2"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U26", "Parent" : "2"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U27", "Parent" : "2"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U28", "Parent" : "2"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U29", "Parent" : "2"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U30", "Parent" : "2"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U31", "Parent" : "2"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U32", "Parent" : "2"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U33", "Parent" : "2"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U34", "Parent" : "2"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U35", "Parent" : "2"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U36", "Parent" : "2"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U37", "Parent" : "2"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U38", "Parent" : "2"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U39", "Parent" : "2"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U40", "Parent" : "2"},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U41", "Parent" : "2"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U42", "Parent" : "2"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U43", "Parent" : "2"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U44", "Parent" : "2"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U45", "Parent" : "2"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U46", "Parent" : "2"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U47", "Parent" : "2"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U48", "Parent" : "2"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U49", "Parent" : "2"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U50", "Parent" : "2"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U51", "Parent" : "2"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U52", "Parent" : "2"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U53", "Parent" : "2"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U54", "Parent" : "2"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U55", "Parent" : "2"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U56", "Parent" : "2"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U57", "Parent" : "2"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U58", "Parent" : "2"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U59", "Parent" : "2"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U60", "Parent" : "2"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U61", "Parent" : "2"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U62", "Parent" : "2"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U63", "Parent" : "2"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U64", "Parent" : "2"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U65", "Parent" : "2"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U66", "Parent" : "2"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U67", "Parent" : "2"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U68", "Parent" : "2"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U69", "Parent" : "2"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U70", "Parent" : "2"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U71", "Parent" : "2"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.mac_muladd_8s_8s_32s_32_4_1_U72", "Parent" : "2"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_352.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv3x3_relu_fu_393.mul_8ns_11ns_19_1_1_U123", "Parent" : "1"},
	{"ID" : "77", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W_fu_479", "Parent" : "0", "Child" : ["78"],
		"CDFG" : "dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "16581393",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"}]},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln112_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln119", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln112", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_scratch", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "COPY_OC_COPY_H_COPY_W", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter18", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter18", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dpu_conv_top_Pipeline_COPY_OC_COPY_H_COPY_W_fu_479.flow_control_loop_pipe_sequential_init_U", "Parent" : "77"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W_fu_493", "Parent" : "0", "Child" : ["80"],
		"CDFG" : "dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "16451598",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln82_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_scratch", "Type" : "None", "Direction" : "I"},
			{"Name" : "lshr_ln1", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln85", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln82", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "POOL_OC_POOL_H_POOL_W", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dpu_conv_top_Pipeline_POOL_OC_POOL_H_POOL_W_fu_493.flow_control_loop_pipe_sequential_init_U", "Parent" : "79"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_0_m_axi_U", "Parent" : "0"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_1_m_axi_U", "Parent" : "0"},
	{"ID" : "86", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_2_m_axi_U", "Parent" : "0"},
	{"ID" : "87", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_3_m_axi_U", "Parent" : "0"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_4_m_axi_U", "Parent" : "0"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_5_m_axi_U", "Parent" : "0"},
	{"ID" : "90", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_6_m_axi_U", "Parent" : "0"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_7_m_axi_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_0_m_axi_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_1_m_axi_U", "Parent" : "0"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_2_m_axi_U", "Parent" : "0"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_3_m_axi_U", "Parent" : "0"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_4_m_axi_U", "Parent" : "0"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_5_m_axi_U", "Parent" : "0"},
	{"ID" : "99", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_6_m_axi_U", "Parent" : "0"},
	{"ID" : "100", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_7_m_axi_U", "Parent" : "0"},
	{"ID" : "101", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"},
	{"ID" : "102", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_8ns_8ns_16_1_1_U182", "Parent" : "0"},
	{"ID" : "103", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_7ns_7ns_14_1_1_U183", "Parent" : "0"},
	{"ID" : "104", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_8ns_16ns_24_1_1_U184", "Parent" : "0"},
	{"ID" : "105", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_8ns_14ns_22_1_1_U185", "Parent" : "0"}]}
