

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "98", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118"],
		"CDFG" : "dpu_conv_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "615", "EstimateLatencyMax" : "167578191",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "21", "Name" : "entry_proc_U0"},
			{"ID" : "22", "Name" : "conv3x3_relu_U0"}],
		"OutputProcess" : [
			{"ID" : "98", "Name" : "Block_entry_proc_U0"},
			{"ID" : "109", "Name" : "Block_entry_proc_2_U0"}],
		"Port" : [
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_0"}]},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_1"}]},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_2"}]},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_3"}]},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_4"}]},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_5"}]},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_6"}]},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem0_7"}]},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_0"}]},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_1"}]},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_2"}]},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_3"}]},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_4"}]},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_5"}]},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_6"}]},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1_7"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "gmem1"}]},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "98", "SubInstance" : "Block_entry_proc_U0", "Port" : "gmem0"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_pool", "Type" : "None", "Direction" : "I"},
			{"Name" : "perf", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "109", "SubInstance" : "Block_entry_proc_2_U0", "Port" : "perf"}]},
			{"Name" : "dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1"},
					{"ID" : "98", "SubInstance" : "Block_entry_proc_U0", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf"}]},
			{"Name" : "dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "conv3x3_relu_U0", "Port" : "dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64"},
					{"ID" : "98", "SubInstance" : "Block_entry_proc_U0", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_0_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_1_m_axi_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_2_m_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_3_m_axi_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_4_m_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_5_m_axi_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_6_m_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_7_m_axi_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_0_m_axi_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_1_m_axi_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_2_m_axi_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_3_m_axi_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_4_m_axi_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_5_m_axi_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_6_m_axi_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_7_m_axi_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "ofmap_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["98"], "DependentChan" : "112", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "ofmap_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "do_pool", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_pool_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["98"], "DependentChan" : "113", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "do_pool_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0", "Parent" : "0", "Child" : ["23", "97"],
		"CDFG" : "conv3x3_relu",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "606", "EstimateLatencyMax" : "150996801",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_0", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_4", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_5", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_6", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem0_7", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_0", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_4", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_5", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_6", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "gmem1_7", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["98"], "DependentChan" : "110",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["98"], "DependentChan" : "111",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Port" : "dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}],
		"Loop" : [
			{"Name" : "OC_LOOP", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "14", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state14"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378", "Parent" : "22", "Child" : ["24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96"],
		"CDFG" : "conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "592", "EstimateLatencyMax" : "2359312",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cycle_count_out_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_flag_0_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_new_0_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_loc_0_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "shl_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln23_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound4", "Type" : "None", "Direction" : "I"},
			{"Name" : "do_relu", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "oc", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln23_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_1_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_3_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_3_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_4_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_4_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_4_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_4_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_5_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_5_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_5_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_5_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_6_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_6_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_6_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_6_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0_7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_7_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_7_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1_7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_7_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem1_7_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "ifmap_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "weight_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "mac_count_flag_3_i_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mac_count_new_3_i_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mac_count_loc_3_i_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "select_ln31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "OH_LOOP_OW_LOOP_IC_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "72", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage15", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage15_subdone", "QuitState" : "ap_ST_fsm_pp0_stage15", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage15_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U5", "Parent" : "23"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U6", "Parent" : "23"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U7", "Parent" : "23"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U8", "Parent" : "23"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U9", "Parent" : "23"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U10", "Parent" : "23"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U11", "Parent" : "23"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U12", "Parent" : "23"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U13", "Parent" : "23"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U14", "Parent" : "23"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U15", "Parent" : "23"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U16", "Parent" : "23"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U17", "Parent" : "23"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U18", "Parent" : "23"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U19", "Parent" : "23"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U20", "Parent" : "23"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U21", "Parent" : "23"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U22", "Parent" : "23"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U23", "Parent" : "23"},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U24", "Parent" : "23"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U25", "Parent" : "23"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U26", "Parent" : "23"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U27", "Parent" : "23"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U28", "Parent" : "23"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U29", "Parent" : "23"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U30", "Parent" : "23"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U31", "Parent" : "23"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U32", "Parent" : "23"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U33", "Parent" : "23"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U34", "Parent" : "23"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U35", "Parent" : "23"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U36", "Parent" : "23"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U37", "Parent" : "23"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U38", "Parent" : "23"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U39", "Parent" : "23"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U40", "Parent" : "23"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U41", "Parent" : "23"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U42", "Parent" : "23"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U43", "Parent" : "23"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U44", "Parent" : "23"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U45", "Parent" : "23"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U46", "Parent" : "23"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U47", "Parent" : "23"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U48", "Parent" : "23"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U49", "Parent" : "23"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U50", "Parent" : "23"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U51", "Parent" : "23"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U52", "Parent" : "23"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U53", "Parent" : "23"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U54", "Parent" : "23"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U55", "Parent" : "23"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U56", "Parent" : "23"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U57", "Parent" : "23"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U58", "Parent" : "23"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U59", "Parent" : "23"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U60", "Parent" : "23"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U61", "Parent" : "23"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U62", "Parent" : "23"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U63", "Parent" : "23"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U64", "Parent" : "23"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U65", "Parent" : "23"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U66", "Parent" : "23"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U67", "Parent" : "23"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U68", "Parent" : "23"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U69", "Parent" : "23"},
	{"ID" : "89", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U70", "Parent" : "23"},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U71", "Parent" : "23"},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U72", "Parent" : "23"},
	{"ID" : "92", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U73", "Parent" : "23"},
	{"ID" : "93", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U74", "Parent" : "23"},
	{"ID" : "94", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U75", "Parent" : "23"},
	{"ID" : "95", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.mac_muladd_8s_8s_32s_32_4_1_U76", "Parent" : "23"},
	{"ID" : "96", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.grp_conv3x3_relu_Pipeline_OH_LOOP_OW_LOOP_IC_LOOP_fu_378.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "97", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv3x3_relu_U0.mul_8ns_11ns_19_1_1_U130", "Parent" : "22"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0", "Parent" : "0", "Child" : ["99", "104"],
		"CDFG" : "Block_entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8", "EstimateLatencyMax" : "16581389",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "do_pool", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["21"], "DependentChan" : "113", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "do_pool_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "99", "SubInstance" : "grp_copy_passthrough_fu_84", "Port" : "gmem0", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "104", "SubInstance" : "grp_maxpool2x2_fu_98", "Port" : "gmem0", "Inst_start_state" : "4", "Inst_end_state" : "3"}]},
			{"Name" : "ofmap", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["21"], "DependentChan" : "112", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "ofmap_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "116", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "117", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "118", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "110",
				"SubConnect" : [
					{"ID" : "99", "SubInstance" : "grp_copy_passthrough_fu_84", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "104", "SubInstance" : "grp_maxpool2x2_fu_98", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Inst_start_state" : "4", "Inst_end_state" : "3"}]},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "111",
				"SubConnect" : [
					{"ID" : "99", "SubInstance" : "grp_copy_passthrough_fu_84", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "104", "SubInstance" : "grp_maxpool2x2_fu_98", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Inst_start_state" : "4", "Inst_end_state" : "3"}]}]},
	{"ID" : "99", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_copy_passthrough_fu_84", "Parent" : "98", "Child" : ["100", "102", "103"],
		"CDFG" : "copy_passthrough",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "16581387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "100", "SubInstance" : "grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64", "Port" : "gmem0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "100", "SubInstance" : "grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "100", "SubInstance" : "grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "100", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_copy_passthrough_fu_84.grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64", "Parent" : "99", "Child" : ["101"],
		"CDFG" : "copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "16581385",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bound7", "Type" : "None", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln119", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "COPY_OC_COPY_H_COPY_W", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter10", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter10", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "101", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_copy_passthrough_fu_84.grp_copy_passthrough_Pipeline_COPY_OC_COPY_H_COPY_W_fu_64.flow_control_loop_pipe_sequential_init_U", "Parent" : "100"},
	{"ID" : "102", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_copy_passthrough_fu_84.mul_8ns_8ns_16_1_1_U183", "Parent" : "99"},
	{"ID" : "103", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_copy_passthrough_fu_84.mul_8ns_16ns_24_1_1_U184", "Parent" : "99"},
	{"ID" : "104", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_maxpool2x2_fu_98", "Parent" : "98", "Child" : ["105", "107", "108"],
		"CDFG" : "maxpool2x2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "4112908",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "105", "SubInstance" : "grp_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W_fu_68", "Port" : "gmem0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_h", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_w", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_ch", "Type" : "None", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "105", "SubInstance" : "grp_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W_fu_68", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "105", "SubInstance" : "grp_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W_fu_68", "Port" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "105", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_maxpool2x2_fu_98.grp_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W_fu_68", "Parent" : "104", "Child" : ["106"],
		"CDFG" : "maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4112906",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bound7", "Type" : "None", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"}]},
			{"Name" : "lshr_ln1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bound", "Type" : "None", "Direction" : "I"},
			{"Name" : "ofmap", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln85", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "POOL_OC_POOL_H_POOL_W", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter11", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter11", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "106", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_maxpool2x2_fu_98.grp_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W_fu_68.flow_control_loop_pipe_sequential_init_U", "Parent" : "105"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_maxpool2x2_fu_98.mul_7ns_7ns_14_1_1_U202", "Parent" : "104"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_maxpool2x2_fu_98.mul_8ns_14ns_22_1_1_U203", "Parent" : "104"},
	{"ID" : "109", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_2_U0", "Parent" : "0",
		"CDFG" : "Block_entry_proc_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "114", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I", "DependentProc" : ["22"], "DependentChan" : "115", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "perf", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "110", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dpu_conv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_1_U", "Parent" : "0"},
	{"ID" : "111", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dpu_mulmulmulmulconv_top_ap_int_64_64_ap_int_64_3_3_ap_int_ap_int_64_64_U", "Parent" : "0"},
	{"ID" : "112", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.ofmap_c_U", "Parent" : "0"},
	{"ID" : "113", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.do_pool_c_U", "Parent" : "0"},
	{"ID" : "114", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mac_count_U", "Parent" : "0"},
	{"ID" : "115", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cycle_count_U", "Parent" : "0"},
	{"ID" : "116", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_h_c_channel_U", "Parent" : "0"},
	{"ID" : "117", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_w_c_channel_U", "Parent" : "0"},
	{"ID" : "118", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_ch_c_channel_U", "Parent" : "0"}]}
