// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        bound7,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1,
        lshr_ln1,
        bound,
        ofmap,
        zext_ln85
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [21:0] bound7;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1;
input  [6:0] lshr_ln1;
input  [13:0] bound;
input  [63:0] ofmap;
input  [6:0] zext_ln85;

reg ap_idle;
reg m_axi_gmem0_0_AWVALID;
reg m_axi_gmem0_0_WVALID;
reg m_axi_gmem0_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_744;
reg   [0:0] first_iter_0_reg_744_pp0_iter3_reg;
reg    ap_block_state5_io_grp1;
reg   [0:0] icmp_ln89_2_reg_748;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter10_reg;
reg    ap_block_state12_pp0_stage0_iter11_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln85_fu_254_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    gmem0_blk_n_B;
reg    gmem0_blk_n_AW;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln85_cast_fu_219_p1;
reg   [63:0] zext_ln85_cast_reg_684;
reg   [0:0] icmp_ln85_reg_689;
reg   [0:0] icmp_ln85_reg_689_pp0_iter2_reg;
wire   [0:0] icmp_ln87_fu_265_p2;
reg   [0:0] icmp_ln87_reg_693;
reg   [0:0] icmp_ln87_reg_693_pp0_iter2_reg;
reg   [6:0] oh_1_reg_703;
reg   [7:0] oc_1_reg_708;
wire   [7:0] add_ln85_fu_303_p2;
reg   [7:0] add_ln85_reg_713;
wire   [0:0] select_ln85_3_fu_326_p3;
reg   [0:0] select_ln85_3_reg_718;
wire   [5:0] trunc_ln87_fu_340_p1;
reg   [5:0] trunc_ln87_reg_723;
wire   [6:0] add_ln87_fu_344_p2;
reg   [6:0] add_ln87_reg_728;
wire   [6:0] ow_mid2_fu_355_p3;
reg   [6:0] ow_mid2_reg_733;
wire   [6:0] select_ln87_fu_363_p3;
reg   [6:0] select_ln87_reg_738;
wire   [0:0] first_iter_0_fu_371_p2;
wire   [0:0] icmp_ln89_2_fu_383_p2;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter3_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter4_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter5_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter6_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter7_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter8_reg;
reg   [0:0] icmp_ln89_2_reg_748_pp0_iter9_reg;
reg   [63:0] gmem0_addr_reg_752;
wire   [7:0] m0_fu_595_p3;
reg   [7:0] m0_reg_783;
wire   [7:0] m1_fu_609_p3;
reg   [7:0] m1_reg_789;
wire   [7:0] select_ln98_fu_621_p3;
reg   [7:0] select_ln98_reg_795;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [63:0] zext_ln91_4_fu_565_p1;
wire   [63:0] zext_ln93_1_fu_577_p1;
wire   [63:0] add_ln91_1_mid2_fu_488_p2;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [6:0] ow_fu_100;
wire   [6:0] add_ln89_fu_377_p2;
wire    ap_loop_init;
reg   [6:0] oh_fu_104;
reg   [13:0] indvar_flatten_fu_108;
wire   [13:0] select_ln87_1_fu_276_p3;
wire    ap_block_pp0_stage0;
reg   [7:0] oc_fu_112;
wire   [7:0] select_ln85_4_fu_333_p3;
reg   [21:0] indvar_flatten27_fu_116;
wire   [21:0] add_ln85_1_fu_259_p2;
reg    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1_local;
reg    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local;
reg    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1_local;
reg    dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local;
wire   [13:0] add_ln87_1_fu_270_p2;
wire   [0:0] icmp_ln89_fu_316_p2;
wire   [0:0] icmp_ln89_1_fu_321_p2;
wire   [6:0] select_ln85_fu_309_p3;
wire   [0:0] empty_fu_350_p2;
wire   [19:0] shl_ln_fu_403_p3;
wire   [12:0] shl_ln91_1_fu_414_p3;
wire   [20:0] zext_ln87_fu_410_p1;
wire   [20:0] zext_ln91_fu_421_p1;
wire   [19:0] shl_ln91_mid1_fu_431_p3;
wire   [19:0] select_ln85_1_fu_438_p3;
wire   [20:0] zext_ln85_2_fu_449_p1;
wire   [20:0] add_ln91_fu_425_p2;
wire   [12:0] shl_ln91_1_mid1_fu_460_p3;
wire   [20:0] zext_ln85_1_fu_445_p1;
wire   [20:0] zext_ln91_1_fu_467_p1;
wire   [20:0] add_ln91_1_fu_471_p2;
wire   [20:0] select_ln85_2_fu_453_p3;
wire   [20:0] add_ln91_1_mid2_v_fu_477_p3;
wire   [63:0] add_ln91_1_mid2_v_cast_fu_484_p1;
wire   [7:0] shl_ln91_2_fu_506_p3;
wire   [11:0] tmp_fu_499_p3;
wire   [11:0] zext_ln91_2_fu_513_p1;
wire   [11:0] add_ln91_2_fu_517_p2;
wire   [7:0] or_ln_fu_531_p3;
wire   [11:0] zext_ln93_fu_538_p1;
wire   [11:0] add_ln93_fu_542_p2;
wire   [16:0] tmp_1_fu_523_p3;
wire   [16:0] zext_ln91_3_fu_556_p1;
wire   [16:0] add_ln91_3_fu_559_p2;
wire   [16:0] tmp_2_fu_548_p3;
wire   [16:0] add_ln93_1_fu_571_p2;
wire   [0:0] icmp_ln96_fu_589_p2;
wire   [0:0] icmp_ln97_fu_603_p2;
wire   [0:0] icmp_ln98_fu_617_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ow_fu_100 = 7'd0;
#0 oh_fu_104 = 7'd0;
#0 indvar_flatten_fu_108 = 14'd0;
#0 oc_fu_112 = 8'd0;
#0 indvar_flatten27_fu_116 = 22'd0;
#0 ap_done_reg = 1'b0;
end

dpu_conv_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten27_fu_116 <= 22'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln85_fu_254_p2 == 1'd0))) begin
            indvar_flatten27_fu_116 <= add_ln85_1_fu_259_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 14'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln85_fu_254_p2 == 1'd0))) begin
            indvar_flatten_fu_108 <= select_ln87_1_fu_276_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oc_fu_112 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln85_reg_689 == 1'd0))) begin
            oc_fu_112 <= select_ln85_4_fu_333_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            oh_fu_104 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln85_reg_689 == 1'd0))) begin
            oh_fu_104 <= select_ln87_fu_363_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ow_fu_100 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln85_reg_689 == 1'd0))) begin
            ow_fu_100 <= add_ln89_fu_377_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln85_reg_713 <= add_ln85_fu_303_p2;
        add_ln87_reg_728 <= add_ln87_fu_344_p2;
        first_iter_0_reg_744 <= first_iter_0_fu_371_p2;
        first_iter_0_reg_744_pp0_iter3_reg <= first_iter_0_reg_744;
        gmem0_addr_reg_752 <= add_ln91_1_mid2_fu_488_p2;
        icmp_ln89_2_reg_748 <= icmp_ln89_2_fu_383_p2;
        icmp_ln89_2_reg_748_pp0_iter10_reg <= icmp_ln89_2_reg_748_pp0_iter9_reg;
        icmp_ln89_2_reg_748_pp0_iter3_reg <= icmp_ln89_2_reg_748;
        icmp_ln89_2_reg_748_pp0_iter4_reg <= icmp_ln89_2_reg_748_pp0_iter3_reg;
        icmp_ln89_2_reg_748_pp0_iter5_reg <= icmp_ln89_2_reg_748_pp0_iter4_reg;
        icmp_ln89_2_reg_748_pp0_iter6_reg <= icmp_ln89_2_reg_748_pp0_iter5_reg;
        icmp_ln89_2_reg_748_pp0_iter7_reg <= icmp_ln89_2_reg_748_pp0_iter6_reg;
        icmp_ln89_2_reg_748_pp0_iter8_reg <= icmp_ln89_2_reg_748_pp0_iter7_reg;
        icmp_ln89_2_reg_748_pp0_iter9_reg <= icmp_ln89_2_reg_748_pp0_iter8_reg;
        m0_reg_783 <= m0_fu_595_p3;
        m1_reg_789 <= m1_fu_609_p3;
        oc_1_reg_708 <= oc_fu_112;
        oh_1_reg_703 <= oh_fu_104;
        ow_mid2_reg_733 <= ow_mid2_fu_355_p3;
        select_ln85_3_reg_718 <= select_ln85_3_fu_326_p3;
        select_ln87_reg_738 <= select_ln87_fu_363_p3;
        select_ln98_reg_795 <= select_ln98_fu_621_p3;
        trunc_ln87_reg_723 <= trunc_ln87_fu_340_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln85_reg_689_pp0_iter2_reg <= icmp_ln85_reg_689;
        icmp_ln87_reg_693_pp0_iter2_reg <= icmp_ln87_reg_693;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln85_reg_689 <= icmp_ln85_fu_254_p2;
        icmp_ln87_reg_693 <= icmp_ln87_fu_265_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        zext_ln85_cast_reg_684[6 : 0] <= zext_ln85_cast_fu_219_p1[6 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln85_fu_254_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln85_reg_689_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local = 1'b1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1_local = 1'b1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local = 1'b1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1_local = 1'b1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_744_pp0_iter3_reg == 1'd1))) begin
        gmem0_blk_n_AW = m_axi_gmem0_0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln89_2_reg_748_pp0_iter10_reg == 1'd1))) begin
        gmem0_blk_n_B = m_axi_gmem0_0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_W = m_axi_gmem0_0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_744_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem0_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln89_2_reg_748_pp0_iter10_reg == 1'd1))) begin
        m_axi_gmem0_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_1_fu_259_p2 = (indvar_flatten27_fu_116 + 22'd1);

assign add_ln85_fu_303_p2 = (oc_fu_112 + 8'd1);

assign add_ln87_1_fu_270_p2 = (indvar_flatten_fu_108 + 14'd1);

assign add_ln87_fu_344_p2 = (select_ln85_fu_309_p3 + 7'd1);

assign add_ln89_fu_377_p2 = (ow_mid2_fu_355_p3 + 7'd1);

assign add_ln91_1_fu_471_p2 = (zext_ln85_1_fu_445_p1 + zext_ln91_1_fu_467_p1);

assign add_ln91_1_mid2_fu_488_p2 = (add_ln91_1_mid2_v_cast_fu_484_p1 + ofmap);

assign add_ln91_1_mid2_v_cast_fu_484_p1 = add_ln91_1_mid2_v_fu_477_p3;

assign add_ln91_1_mid2_v_fu_477_p3 = ((select_ln85_3_reg_718[0:0] == 1'b1) ? add_ln91_1_fu_471_p2 : select_ln85_2_fu_453_p3);

assign add_ln91_2_fu_517_p2 = (tmp_fu_499_p3 + zext_ln91_2_fu_513_p1);

assign add_ln91_3_fu_559_p2 = (tmp_1_fu_523_p3 + zext_ln91_3_fu_556_p1);

assign add_ln91_fu_425_p2 = (zext_ln87_fu_410_p1 + zext_ln91_fu_421_p1);

assign add_ln93_1_fu_571_p2 = (tmp_2_fu_548_p3 + zext_ln91_3_fu_556_p1);

assign add_ln93_fu_542_p2 = (tmp_fu_499_p3 + zext_ln93_fu_538_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11_grp1 = ((icmp_ln89_2_reg_748_pp0_iter10_reg == 1'd1) & (m_axi_gmem0_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp1 = ((m_axi_gmem0_0_AWREADY == 1'b0) & (first_iter_0_reg_744_pp0_iter3_reg == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = zext_ln93_1_fu_577_p1;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 = zext_ln91_4_fu_565_p1;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0_local;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 = dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1_local;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = zext_ln93_1_fu_577_p1;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 = zext_ln91_4_fu_565_p1;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0_local;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 = dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1_local;

assign empty_fu_350_p2 = (select_ln85_3_fu_326_p3 | icmp_ln87_reg_693);

assign first_iter_0_fu_371_p2 = ((ow_mid2_fu_355_p3 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_254_p2 = ((indvar_flatten27_fu_116 == bound7) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_265_p2 = ((indvar_flatten_fu_108 == bound) ? 1'b1 : 1'b0);

assign icmp_ln89_1_fu_321_p2 = ((ow_fu_100 == lshr_ln1) ? 1'b1 : 1'b0);

assign icmp_ln89_2_fu_383_p2 = ((add_ln89_fu_377_p2 == lshr_ln1) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_316_p2 = ((lshr_ln1 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_589_p2 = (($signed(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1) > $signed(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_603_p2 = (($signed(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0) > $signed(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_617_p2 = (($signed(m0_reg_783) > $signed(m1_reg_789)) ? 1'b1 : 1'b0);

assign m0_fu_595_p3 = ((icmp_ln96_fu_589_p2[0:0] == 1'b1) ? dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1 : dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1);

assign m1_fu_609_p3 = ((icmp_ln97_fu_603_p2[0:0] == 1'b1) ? dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0 : dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = gmem0_addr_reg_752;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = zext_ln85_cast_reg_684;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_RREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = select_ln98_reg_795;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd1;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign or_ln_fu_531_p3 = {{select_ln87_reg_738}, {1'd1}};

assign ow_mid2_fu_355_p3 = ((empty_fu_350_p2[0:0] == 1'b1) ? 7'd0 : ow_fu_100);

assign select_ln85_1_fu_438_p3 = ((icmp_ln87_reg_693_pp0_iter2_reg[0:0] == 1'b1) ? shl_ln91_mid1_fu_431_p3 : shl_ln_fu_403_p3);

assign select_ln85_2_fu_453_p3 = ((icmp_ln87_reg_693_pp0_iter2_reg[0:0] == 1'b1) ? zext_ln85_2_fu_449_p1 : add_ln91_fu_425_p2);

assign select_ln85_3_fu_326_p3 = ((icmp_ln87_reg_693[0:0] == 1'b1) ? icmp_ln89_fu_316_p2 : icmp_ln89_1_fu_321_p2);

assign select_ln85_4_fu_333_p3 = ((icmp_ln87_reg_693[0:0] == 1'b1) ? add_ln85_fu_303_p2 : oc_fu_112);

assign select_ln85_fu_309_p3 = ((icmp_ln87_reg_693[0:0] == 1'b1) ? 7'd0 : oh_fu_104);

assign select_ln87_1_fu_276_p3 = ((icmp_ln87_fu_265_p2[0:0] == 1'b1) ? 14'd1 : add_ln87_1_fu_270_p2);

assign select_ln87_fu_363_p3 = ((select_ln85_3_fu_326_p3[0:0] == 1'b1) ? add_ln87_fu_344_p2 : select_ln85_fu_309_p3);

assign select_ln98_fu_621_p3 = ((icmp_ln98_fu_617_p2[0:0] == 1'b1) ? m0_reg_783 : m1_reg_789);

assign shl_ln91_1_fu_414_p3 = {{oh_1_reg_703}, {6'd0}};

assign shl_ln91_1_mid1_fu_460_p3 = {{add_ln87_reg_728}, {6'd0}};

assign shl_ln91_2_fu_506_p3 = {{select_ln87_reg_738}, {1'd0}};

assign shl_ln91_mid1_fu_431_p3 = {{add_ln85_reg_713}, {12'd0}};

assign shl_ln_fu_403_p3 = {{oc_1_reg_708}, {12'd0}};

assign tmp_1_fu_523_p3 = {{add_ln91_2_fu_517_p2}, {5'd0}};

assign tmp_2_fu_548_p3 = {{add_ln93_fu_542_p2}, {5'd0}};

assign tmp_fu_499_p3 = {{trunc_ln87_reg_723}, {6'd0}};

assign trunc_ln87_fu_340_p1 = select_ln85_4_fu_333_p3[5:0];

assign zext_ln85_1_fu_445_p1 = select_ln85_1_fu_438_p3;

assign zext_ln85_2_fu_449_p1 = shl_ln91_mid1_fu_431_p3;

assign zext_ln85_cast_fu_219_p1 = zext_ln85;

assign zext_ln87_fu_410_p1 = shl_ln_fu_403_p3;

assign zext_ln91_1_fu_467_p1 = shl_ln91_1_mid1_fu_460_p3;

assign zext_ln91_2_fu_513_p1 = shl_ln91_2_fu_506_p3;

assign zext_ln91_3_fu_556_p1 = ow_mid2_reg_733;

assign zext_ln91_4_fu_565_p1 = add_ln91_3_fu_559_p2;

assign zext_ln91_fu_421_p1 = shl_ln91_1_fu_414_p3;

assign zext_ln93_1_fu_577_p1 = add_ln93_1_fu_571_p2;

assign zext_ln93_fu_538_p1 = or_ln_fu_531_p3;

always @ (posedge ap_clk) begin
    zext_ln85_cast_reg_684[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //dpu_conv_top_maxpool2x2_Pipeline_POOL_OC_POOL_H_POOL_W
