// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dpu_conv_top_Block_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        do_pool_dout,
        do_pool_empty_n,
        do_pool_read,
        do_pool_num_data_valid,
        do_pool_fifo_cap,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        ofmap_dout,
        ofmap_empty_n,
        ofmap_read,
        ofmap_num_data_valid,
        ofmap_fifo_cap,
        p_read,
        p_read1,
        p_read2,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1,
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] do_pool_dout;
input   do_pool_empty_n;
output   do_pool_read;
input  [2:0] do_pool_num_data_valid;
input  [2:0] do_pool_fifo_cap;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] ofmap_dout;
input   ofmap_empty_n;
output   ofmap_read;
input  [2:0] ofmap_num_data_valid;
input  [2:0] ofmap_fifo_cap;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0;
output  [16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1;
output   dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;
input  [7:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg do_pool_read;
reg m_axi_gmem0_0_AWVALID;
reg[63:0] m_axi_gmem0_0_AWADDR;
reg[0:0] m_axi_gmem0_0_AWID;
reg[31:0] m_axi_gmem0_0_AWLEN;
reg[2:0] m_axi_gmem0_0_AWSIZE;
reg[1:0] m_axi_gmem0_0_AWBURST;
reg[1:0] m_axi_gmem0_0_AWLOCK;
reg[3:0] m_axi_gmem0_0_AWCACHE;
reg[2:0] m_axi_gmem0_0_AWPROT;
reg[3:0] m_axi_gmem0_0_AWQOS;
reg[3:0] m_axi_gmem0_0_AWREGION;
reg[0:0] m_axi_gmem0_0_AWUSER;
reg m_axi_gmem0_0_WVALID;
reg[7:0] m_axi_gmem0_0_WDATA;
reg[0:0] m_axi_gmem0_0_WSTRB;
reg m_axi_gmem0_0_WLAST;
reg[0:0] m_axi_gmem0_0_WID;
reg[0:0] m_axi_gmem0_0_WUSER;
reg m_axi_gmem0_0_BREADY;
reg ofmap_read;
reg[16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
reg dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
reg dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
reg[16:0] dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
reg dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
reg dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    do_pool_blk_n;
reg    ofmap_blk_n;
reg   [7:0] p_read_5_reg_112;
reg    ap_block_state1;
reg   [7:0] p_read14_reg_118;
reg   [7:0] p_read_6_reg_124;
wire   [0:0] do_pool_read_read_fu_72_p2;
reg   [0:0] do_pool_read_reg_130;
reg   [63:0] ofmap_read_reg_134;
wire    grp_copy_passthrough_fu_84_ap_start;
wire    grp_copy_passthrough_fu_84_ap_done;
wire    grp_copy_passthrough_fu_84_ap_idle;
wire    grp_copy_passthrough_fu_84_ap_ready;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID;
wire   [31:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARID;
wire   [31:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARUSER;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_RREADY;
wire    grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY;
wire   [16:0] grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
wire    grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
wire   [16:0] grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
wire    grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
wire    grp_maxpool2x2_fu_98_ap_start;
wire    grp_maxpool2x2_fu_98_ap_done;
wire    grp_maxpool2x2_fu_98_ap_idle;
wire    grp_maxpool2x2_fu_98_ap_ready;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID;
wire   [31:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID;
wire   [7:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARID;
wire   [31:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARUSER;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_RREADY;
wire    grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY;
wire   [16:0] grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
wire    grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
wire   [16:0] grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1;
wire    grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
wire   [16:0] grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
wire    grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
wire   [16:0] grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1;
wire    grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;
reg    grp_copy_passthrough_fu_84_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_maxpool2x2_fu_98_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    ap_block_state3_on_subcall_done;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_copy_passthrough_fu_84_ap_start_reg = 1'b0;
#0 grp_maxpool2x2_fu_98_ap_start_reg = 1'b0;
end

dpu_conv_top_copy_passthrough grp_copy_passthrough_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_copy_passthrough_fu_84_ap_start),
    .ap_done(grp_copy_passthrough_fu_84_ap_done),
    .ap_idle(grp_copy_passthrough_fu_84_ap_idle),
    .ap_ready(grp_copy_passthrough_fu_84_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(m_axi_gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(m_axi_gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_copy_passthrough_fu_84_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(grp_copy_passthrough_fu_84_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(8'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(11'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(m_axi_gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(m_axi_gmem0_0_BRESP),
    .m_axi_gmem0_0_BID(m_axi_gmem0_0_BID),
    .m_axi_gmem0_0_BUSER(m_axi_gmem0_0_BUSER),
    .ofmap(ofmap_read_reg_134),
    .in_h(p_read_6_reg_124),
    .in_w(p_read14_reg_118),
    .out_ch(p_read_5_reg_112),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0(grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0(grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0(grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0(grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0)
);

dpu_conv_top_maxpool2x2 grp_maxpool2x2_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_maxpool2x2_fu_98_ap_start),
    .ap_done(grp_maxpool2x2_fu_98_ap_done),
    .ap_idle(grp_maxpool2x2_fu_98_ap_idle),
    .ap_ready(grp_maxpool2x2_fu_98_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(m_axi_gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(m_axi_gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_maxpool2x2_fu_98_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(grp_maxpool2x2_fu_98_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(8'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(11'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(m_axi_gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(m_axi_gmem0_0_BRESP),
    .m_axi_gmem0_0_BID(m_axi_gmem0_0_BID),
    .m_axi_gmem0_0_BUSER(m_axi_gmem0_0_BUSER),
    .ofmap(ofmap_read_reg_134),
    .in_h(p_read_6_reg_124),
    .in_w(p_read14_reg_118),
    .out_ch(p_read_5_reg_112),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_q1),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q0),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1(grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1),
    .dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1(dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_copy_passthrough_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_copy_passthrough_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_copy_passthrough_fu_84_ap_ready == 1'b1)) begin
            grp_copy_passthrough_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_maxpool2x2_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_maxpool2x2_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_maxpool2x2_fu_98_ap_ready == 1'b1)) begin
            grp_maxpool2x2_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        do_pool_read_reg_130 <= do_pool_dout;
        ofmap_read_reg_134 <= ofmap_dout;
        p_read14_reg_118 <= p_read1;
        p_read_5_reg_112 <= p_read2;
        p_read_6_reg_124 <= p_read;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        do_pool_blk_n = do_pool_empty_n;
    end else begin
        do_pool_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        do_pool_read = 1'b1;
    end else begin
        do_pool_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((do_pool_read_reg_130 == 1'd1)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
        end else if ((do_pool_read_reg_130 == 1'd0)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0;
        end else begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = 'bx;
        end
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((do_pool_read_reg_130 == 1'd1)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
        end else if ((do_pool_read_reg_130 == 1'd0)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0;
        end else begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = 1'b0;
        end
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((do_pool_read_reg_130 == 1'd1)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
        end else if ((do_pool_read_reg_130 == 1'd0)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0;
        end else begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = 'bx;
        end
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((do_pool_read_reg_130 == 1'd1)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
        end else if ((do_pool_read_reg_130 == 1'd0)) begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = grp_copy_passthrough_fu_84_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0;
        end else begin
            dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = 1'b0;
        end
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1))) begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1;
    end else begin
        dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWADDR = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWADDR = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWADDR;
    end else begin
        m_axi_gmem0_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWBURST = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWBURST = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWBURST;
    end else begin
        m_axi_gmem0_0_AWBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWCACHE = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWCACHE = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWCACHE;
    end else begin
        m_axi_gmem0_0_AWCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWID = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWID = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWID;
    end else begin
        m_axi_gmem0_0_AWID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWLEN = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWLEN = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLEN;
    end else begin
        m_axi_gmem0_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWLOCK = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWLOCK = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWLOCK;
    end else begin
        m_axi_gmem0_0_AWLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWPROT = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWPROT = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWPROT;
    end else begin
        m_axi_gmem0_0_AWPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWQOS = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWQOS = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWQOS;
    end else begin
        m_axi_gmem0_0_AWQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWREGION = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWREGION = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWREGION;
    end else begin
        m_axi_gmem0_0_AWREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWSIZE = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWSIZE = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWSIZE;
    end else begin
        m_axi_gmem0_0_AWSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWUSER = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWUSER = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWUSER;
    end else begin
        m_axi_gmem0_0_AWUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_AWVALID = grp_maxpool2x2_fu_98_m_axi_gmem0_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_AWVALID = grp_copy_passthrough_fu_84_m_axi_gmem0_0_AWVALID;
    end else begin
        m_axi_gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_BREADY = grp_maxpool2x2_fu_98_m_axi_gmem0_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_BREADY = grp_copy_passthrough_fu_84_m_axi_gmem0_0_BREADY;
    end else begin
        m_axi_gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WDATA = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WDATA = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WDATA;
    end else begin
        m_axi_gmem0_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WID = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WID = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WID;
    end else begin
        m_axi_gmem0_0_WID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WLAST = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WLAST = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WLAST;
    end else begin
        m_axi_gmem0_0_WLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WSTRB = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WSTRB = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WSTRB;
    end else begin
        m_axi_gmem0_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WUSER = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WUSER = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WUSER;
    end else begin
        m_axi_gmem0_0_WUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd1)))) begin
        m_axi_gmem0_0_WVALID = grp_maxpool2x2_fu_98_m_axi_gmem0_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state3) & (do_pool_read_reg_130 == 1'd0)))) begin
        m_axi_gmem0_0_WVALID = grp_copy_passthrough_fu_84_m_axi_gmem0_0_WVALID;
    end else begin
        m_axi_gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofmap_blk_n = ofmap_empty_n;
    end else begin
        ofmap_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ofmap_read = 1'b1;
    end else begin
        ofmap_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (do_pool_read_read_fu_72_p2 == 1'd1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state1) & (do_pool_read_read_fu_72_p2 == 1'd0) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ofmap_empty_n == 1'b0) | (do_pool_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((grp_maxpool2x2_fu_98_ap_done == 1'b0) & (do_pool_read_reg_130 == 1'd1)) | ((grp_copy_passthrough_fu_84_ap_done == 1'b0) & (do_pool_read_reg_130 == 1'd0)));
end

assign do_pool_read_read_fu_72_p2 = do_pool_dout;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_1_address1;

assign dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1 = grp_maxpool2x2_fu_98_dpu_conv_top_ap_int_8_64_64_ap_int_8_64_3_3_ap_int_32_ap_int_8_64_64_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_8_ap_uint_1_ap_uint_1_perf_counters_t_conv_buf_address1;

assign grp_copy_passthrough_fu_84_ap_start = grp_copy_passthrough_fu_84_ap_start_reg;

assign grp_maxpool2x2_fu_98_ap_start = grp_maxpool2x2_fu_98_ap_start_reg;

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_RREADY = 1'b0;

endmodule //dpu_conv_top_Block_entry_proc
